### PR TITLE
Adding CDS bootstrapping

### PR DESCRIPTION
**Pull request by farzadwp**
In this commit I have 

- Added new classes to contain CDS, survival probabilities, and hazard rates curves;
- Added new classes to contain CDS curve specifications;
- Added generic methods to format and print for the above classes; and
- Created bootsrapping generic methods

All of the new classes and methods contain full documentation with examples
@imanuelcostigan

### CODE REVIEW

**Review by imanuelcostigan — CHANGES_REQUESTED** [review]
Questions:

1. Is there a nice way that you can combine the `HazardCurve` and `SurvivalCurve` classes into one? Looks like the only reason for separating them is because `credule::bootstrapCDS()` returns hazard rates and survival probabilities in one object and you want to distinguish them. Possibilities:
      * can you extend `CDSCurve` by including `hazard_rates` and `survival_probabilities` fields which are set to `NA_numeric` if the instance is not bootstrapped and otherwise the bootstrapped values? OR
      * define a class called `BoostrappedCDSCurve` which includes `hazard_rates` and `survival_probabilities` fields (plus others) which is returned by `bootstrap()` where the latter is a generic that replaces `bootstrap_survprob()` and `bootstrap_harzardrate()`. 
2. Where do the valid rank labels come from? Would be better if we could make these nicer labels that have a consistent convention. All lower case would be better (the user doesn't have to remember). For eg. Senior -> "senior", SubTier3 -> "sub_tier_3", SubTier2Upper -> "sub_tier_2_upper", SubTier2Lower -> "sub_tier_2_lower", SubTier1 -> "sub_tier_1"

Actions:

- [ ] I have added a few commits to yours on the `imanuelcostigan:feature-cds-ic` branch. (Long story about why I did this). Can you merge these into your fork? Happy to show you how to do this.
- [ ] Please review my commit commentary to understand my changes. 
- [ ] Update your version of roxygen2
- [ ] Use the print / format pattern of the `ZeroCurve` class for the various credit curve classes you have introduced (main thing is that it goes via a tibble).
- [ ] Document whether the `probabilities` passed to `SurvivalProbCurve` are cumulative or marginal survival probabilities
- [ ] Review the CONTRIBUTING file on the repo as it relates to PR and make sure you have added test cases, updated the NEWS file, etc
- [ ] Update the README.Rmd (and knit the corresponding README.md file) 
- [ ] Create a vignette for the credit curve functionality
- [ ] Ensure there are no errors, warnings or notes returning from `devtools::check()`

**Comment by farzadwp** [comment]
1- In this iteration, the new credit classes mirror interest rate classes in functionality, as follows:
SurvivalProbabilities <-> DiscountFactors
ZeroHazardRate <-> InterestRate
CreditCurve <-> ZeroCurve

2- I have limited the use of Credule package (for bootstrapping) to only one generic: as_SurvivalProbabilities.CDSCurve 

3- CreditCurve constructor only needs Survival Probabilities, so it doesn't have any dependency on the bootstrapping. I chose the name CreditCurve instead of the suggested BootstarppedCDSCurve, because the class no longer depends on bootstrapping.

4- Zero Hazard rates are now calculated from Survival Probabilities, without having to do an additional bootstrapping. (This is to ensure internal consistency in terms of business conventions)  

5- I have extended all of the interpolation generic functions, to mimic similar functionalities for the credit classes. Here, note that
I overload interpolate_dfs with CreditCurve, instead of defining a new generic (e.g. interpolate_sps)

6- There are additional rules for CDSSpecs in cred-ops. When output specs are ambiguous, they are replaced with an "Empty" CDSSpecs object. 

7- for +,-,/ and *, I included an assertion to check if the length of objects are equal. In IR and DF operators, if the length are not equal, equally lengthed vectors are created. I suggest including an assertion for IR and DF operators as well. 

-------
Point-to-point responses to comments:
-------
Question 1- In this iteration, Credit Curve holds that responsibility, in the same way that ZeroCurve does for rates.
Question 2- Discussed in the meeting
Action 1 - Done
Action 2- Done
Action 3- I updated my Roxygen2 to 6.1.0
Action 4- Done
Action 5- I added this to as_SurvivalProbabilities.CDSCurve
Action 6- I added some tests on the important functions. Note that context() is being deprecated, so I did not use it.
Action 7- Done
Action 8- Check() fails on running fmbasics-Ex.R, which I did not edit. I haven't been able to figure out the cause of the issue.

**Review by imanuelcostigan — CHANGES_REQUESTED** [review]
Please:

1. refresh your PR from master and resolve conflicts
2. make sure all checks pass with no warnings, notes etc

**Comment by farzadwp** [comment]
Please review the pull request. I have 
1- refreshed your PR from master and resolve conflicts
2- resolved errors, warnings, and notes

**Pull request merged**
